### ISSUE TITLE
Hackathon dealing with consolidate.js and filters (Swig)

### ISSUE THREAD

**Issue by netpoetica** [tj/consolidate.js#168]
It's hard to tell if this is a consolidatejs problem or an Express problem, but in order to extend swig and add new filters, you need to have a reference to the instance of swig later. consolidate.js wraps swig and hides the reference to the instance (i.e. you cannot call `cons.swig.setFilter`), so in order to add new filters you have to actually include swig yourself:

```
var express = require('express'),
    app = express(),
    swig = require('swig'),
    cons = require('consolidate');

app.engine('html', cons.swig);

var filters = require('./filters');
swig.setFilter('modifier', filters.modifier);
```

Looks like a major hackathon to me. Either app.engine() should return the original instance, or consolidate should provide access to the original object somehow. Maybe it already does?

**Comment by yoshokatana** [comment]
Yeah, it doesn't expose that anywhere. @doowb any thoughts on exposing it? That'd allow devs to handle pretty much half of all the open tickets in this repo.

**Comment by doowb** [comment]
When first reading this issue, I thought it wasn't needed because you should be able to just require in an engine outside of consolidate and use it's methods directly (like @netpoetica mentions in the original post). This only works if the engine ensures that it's created as a singleton, and not all engines do that.

I'll expose (or accept a PR that exposes)  `requires` so this ensures the same instance of an engine can be used.

**Comment by yoshokatana** [comment]
Sounds good!

**Comment by yoshokatana** [comment]
Added it as `requires` in PR #187

**Comment by doowb** [comment]
Sounds like this was resolved, I'm going to close but please feel free to reopen or create a new issue if:
- the bug is still happening
- you're still having problems
