### ISSUE TITLE
cons.requires vs global instances

### ISSUE THREAD

**Issue by ismay** [tj/consolidate.js#203]
Consolidate will pick up a global handlebars instance, and seems to do this for other languages as well. Is this something that works for all supported templating languages, or is it advisable to use `cons.requires`?

**Comment by doowb** [comment]
If you need to configure something on an engine instance, then use `cons.requires` and setup the template engine instance the way you need it before using `cons[engine]`.

It happens to work for `handlebars` because node caches calls to `require` and it's technically the same "instance" of Handlebars at that point. For other engines like `nunjucks` mentioned in the other issue, you have to manually create an instance of nunjucks to set the properties on and then set that on `cons.requires` so it can be used inside consolidate.

Hope this helps.

**Comment by ismay** [comment]
Yeah it does. Thanks for the explanation!
