### ISSUE TITLE
How are missing partial extensions resolved for readPartials?

### ISSUE THREAD

**Issue by ismay** [tj/consolidate.js#207]
I've been trying to figure out how consolidate does this, but haven't been able to. I'd like to know because I'm shimming partial functionality for a library that uses the `.render` method, and thus skips the `readPartials` method.

Because it seems like consolidate corrects the missing extension [here](https://github.com/superwolff/metalsmith-layouts/blob/master/test/index.js#L82) to `nav.html`. I'm just wondering what's going on exactly, so I can replicate the logic for my shim, and provide a consistent interface for end-users.

**Comment by doowb** [comment]
It uses the `ext` of the template being rendered: https://github.com/tj/consolidate.js/blob/master/lib/consolidate.js#L123

**Comment by ismay** [comment]
Ok, so if only `engine` is known, there's no way to export that extension right? (so it can be used by other libraries)

**Comment by doowb** [comment]
`path` in the code above is the path to the template file being rendered... so it might be something like `views/home.html`. Then `includes/nav` would resolve to `views/includes/nav.html` because it's looking for the partials in the same directory as the template (`views`), using the key provided (`includes/nav`) and the same extension as the template (`.html`).

Consuming applications like `express` handle finding the template file based on the `view engine` specified, which in this case would be `html`. And the engine is configured like `app.engine('html', consolidate.swig)`, so this maps any `html` files to `swig`. There is an assumption that any partials are going to use the same extension as the template that they're included in.

I'm not sure how metalsmith handles it.

**Comment by ismay** [comment]
> There is an assumption that any partials are going to use the same extension as the template that they're included in.

That makes sense. Thanks for explaining. I know that this might be somewhat out of scope for this issue tracker, so I appreciate it!

**Comment by doowb** [comment]
No problem. I'm going to close this. Feel free to keep posting if you have any other questions.
